In [1]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing.transactionencoder import TransactionEncoder
import csv
import os
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [13]:
# 读取原始数据
movies = pd.read_csv('movie (2).csv')
movies.head(10)

   类型                  主演    地区     导演  特色   评分     电影名
0  剧情    徐峥|王传君|周一围|谭卓|章宇  中国大陆    文牧野  经典  8.9   我不是药神
1  剧情   冯小刚|许晴|张涵予|刘桦|李易峰  中国大陆     管虎  经典  7.8     老炮儿
2  剧情  王宝强|刘昊然|肖央|刘承羽|尚语贤  中国大陆    陈思诚  经典  6.7  唐人街探案2
3  剧情  任素汐|大力|刘帅良|裴魁山|阿如那  中国大陆  周申|刘露  经典  8.3     驴得水
4  剧情   徐峥|王宝强|李曼|李小璐|左小青  中国大陆    叶伟民  经典  7.5    人在囧途
5  剧情    徐峥|黄渤|余男|多布杰|王双宝  中国大陆     宁浩  经典  8.1     无人区
6  剧情  姜文|香川照之|袁丁|姜宏波|丛志军  中国大陆     姜文  经典  9.2    鬼子来了
7  剧情  章子怡|黄晓明|张震|王力宏|陈楚生  中国大陆    李芳芳  经典  7.6    无问西东
8  剧情     彭于晏|廖凡|姜文|周韵|许晴  中国大陆     姜文  经典  7.1    邪不压正
9  剧情      肖央|王太利|韩秋池|于蓓蓓  中国大陆     肖央  经典  8.5  11度青春之

In [4]:
movi2=movies[movies['地区']=='香港']

In [7]:
movi2.shape

(7014, 7)

In [8]:
movi2.to_csv('hkmovie.csv')

In [3]:
movi2=movies[movies['地区']=='台湾']

In [51]:
movi2.head()

       类型                   主演  地区   导演  特色   评分           电影名
10113  剧情   柯震东|陈妍希|敖犬|郝劭文|蔡昌宪  台湾  九把刀  经典  8.1  那些年，我们一起追的女孩
10114  剧情  杨千嬅|余文乐|黄德斌|陈逸宁|谷祖琳  台湾  彭浩翔  经典  8.0         志明与春娇
10115  剧情  张国荣|张曼玉|梁朝伟|林青霞|张学友  台湾  王家卫  经典  8.6          东邪西毒
10116  剧情    梁朝伟|汤唯|陈冲|王力宏|庹宗华  台湾   李安  经典  8.2           色，戒
10117  剧情   郎雄|杨贵媚|吴倩莲|王渝文|张艾嘉  台湾   李安  经典  9.1          饮食男女

In [52]:
movi2.shape

(2734, 7)

In [53]:
movi2.to_csv('twwmovie.csv')

In [66]:
movies['地区'].value_counts()

美国      29366
中国大陆     9071
日本       8979
香港       7014
法国       6173
英国       5804
韩国       4893
德国       4096
台湾       2734
加拿大      2641
意大利      2405
印度       2081
西班牙      1748
泰国       1331
澳大利亚     1292
俄罗斯      1116
爱尔兰       605
丹麦        575
瑞典        559
巴西        473
伊朗        204
Name: 地区, dtype: int64

In [14]:
movi2=movies[movies['地区']=='日本']

In [68]:
movi2.to_csv('jpmovie.csv')

In [79]:
movi2=movies[movies['地区']=='韩国']

In [80]:
movi2.to_csv('krmovie.csv')

# 1

In [10]:
mov=movi2[['电影名','主演']]
mov.head()

            电影名                   主演
8523       霸王别姬     张国荣|张丰毅|巩俐|葛优|英达
8524  大话西游之大圣娶亲   周星驰|吴孟达|朱茵|蔡少芬|蓝洁瑛
8525  大话西游之月光宝盒  周星驰|吴孟达|罗家英|蓝洁瑛|莫文蔚
8526        无间道  刘德华|梁朝伟|黄秋生|曾志伟|郑秀文
8527     唐伯虎点秋香   周星驰|巩俐|陈百祥|郑佩佩|朱咪咪

In [11]:
# 第一步，将原始数据转化为标准格式
movies_standard = mov.drop('主演', 1).join(mov['主演'].str.get_dummies())

D:\soft\python\Lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [12]:
movies_standard.columns

Index(['电影名', 'Angus Macfadyen', 'Buxx Banner', 'Cici Lau', 'Dan Glenn',
       'Daniel Dae Kim', 'Fatma Girik', 'Fay Ann Lee', 'Gale Harold', 'Guns',
       ...
       '黎骏', '黑川力矢', '黛比·玛扎', '龍天生', '龙刚', '龙剑笙', '龙天生', '龙方', '龚国强', '龚秋霞'],
      dtype='object', length=2322)

In [14]:
# 利用mlxtend提供的apriori算法函数得到频繁项集，其中设置最小支持度为0.05
movies_standard.set_index(['电影名'], inplace=True)

In [43]:
frequent_item_sets = apriori(movies_standard, min_support=0.003, use_colnames=True)
print(frequent_item_sets)

D:\soft\python\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:113: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  DeprecationWarning,

      support                   itemsets
0    0.013117                      (万梓良)
1    0.005845                       (乔宏)
2    0.006843                      (于荣光)
3    0.004990                      (井柏然)
4    0.003279                       (井莉)
..        ...                        ...
501  0.003279        (蓝洁瑛, 蔡少芬, 周星驰, 朱茵)
502  0.003279       (罗家英, 蓝洁瑛, 莫文蔚, 周星驰)
503  0.003137  (郑秀文, 刘德华, 胡燕妮, 吴嘉龙, 林家栋)
504  0.003279   (吴孟达, 周星驰, 蓝洁瑛, 蔡少芬, 朱茵)
505  0.003279  (吴孟达, 莫文蔚, 周星驰, 蓝洁瑛, 罗家英)

[506 rows x 2 columns]

In [49]:
frequent_item_sets.sort_values(by='support',ascending=False)

      support    itemsets
32   0.063587       (刘德华)
129  0.039350       (曾志伟)
71   0.037782       (周星驰)
72   0.035928       (周润发)
57   0.035786       (吴君如)
..        ...         ...
409  0.003137  (黄秋生, 张耀扬)
271  0.003137       (郑文雅)
402  0.003137  (张学友, 曾志伟)
87   0.003137       (尹子维)
423  0.003137  (郑秀文, 林家栋)

[506 rows x 2 columns]

In [48]:
# 计算规则，并设置提升度阈值为 1.25 （返回的是各个指标的数值，可以按照按兴趣的指标排序观察，但具体解释还得参考实际数据的含义）
rules = association_rules(frequent_item_sets, metric='confidence', min_threshold=0.07)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(刘德华),(万梓良),0.063587,0.013117,0.005988,0.094170,7.179470,0.005154,1.089480,0.919161
1,(万梓良),(刘德华),0.013117,0.063587,0.005988,0.456522,7.179470,0.005154,1.723000,0.872154
2,(任达华),(林雪),0.034217,0.020245,0.003564,0.104167,5.145246,0.002872,1.093680,0.834190
3,(林雪),(任达华),0.020245,0.034217,0.003564,0.176056,5.145246,0.002872,1.172147,0.822293
4,(余文乐),(曾志伟),0.015398,0.039350,0.003422,0.222222,5.647343,0.002816,1.235122,0.835795
...,...,...,...,...,...,...,...,...,...,...
769,(吴孟达),"(罗家英, 蓝洁瑛, 莫文蔚, 周星驰)",0.034645,0.003279,0.003279,0.094650,28.864198,0.003166,1.100923,1.000000
770,(莫文蔚),"(蓝洁瑛, 罗家英, 吴孟达, 周星驰)",0.018392,0.003279,0.003279,0.178295,54.372093,0.003219,1.212990,1.000000
771,(周星驰),"(蓝洁瑛, 罗家英, 吴孟达, 莫文蔚)",0.037782,0.003279,0.003279,0.086792,26.467925,0.003155,1.091451,1.000000
772,(蓝洁瑛),"(罗家英, 吴孟达, 莫文蔚, 周星驰)",0.009552,0.003279,0.003279,0.343284,104.686567,0.003248,1.517734,1.000000
773,(罗家英),"(蓝洁瑛, 吴孟达, 莫文蔚, 周星驰)",0.014970,0.003279,0.003279,0.219048,66.800000,0.003230,1.276289,1.000000

# 2

In [4]:
mov=movi2[['电影名','主演']]
mov.head()

                电影名                   主演
10113  那些年，我们一起追的女孩   柯震东|陈妍希|敖犬|郝劭文|蔡昌宪
10114         志明与春娇  杨千嬅|余文乐|黄德斌|陈逸宁|谷祖琳
10115          东邪西毒  张国荣|张曼玉|梁朝伟|林青霞|张学友
10116           色，戒    梁朝伟|汤唯|陈冲|王力宏|庹宗华
10117          饮食男女   郎雄|杨贵媚|吴倩莲|王渝文|张艾嘉

In [5]:
# 第一步，将原始数据转化为标准格式
movies_standard = mov.drop('主演', 1).join(mov['主演'].str.get_dummies())

D:\soft\python\Lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [6]:
movies_standard.columns

Index(['电影名', 'BEN', 'Ben', 'Chia-lun Chu', 'DANNY', 'Danny Ravebeck',
       'Edowan Bersmea', 'HOTPINK', 'Hold住姐，Miss Lin', 'Isabelle Corona',
       ...
       '黄鸿升(小鬼)', '黑木美沙', '齊秦', '齐丽丽', '齐秦', '龍冠武', '龐嘉綾', '龙劭华', '龙飞', '龚钰祺'],
      dtype='object', length=1513)

In [7]:
# 利用mlxtend提供的apriori算法函数得到频繁项集，其中设置最小支持度为0.05
movies_standard.set_index(['电影名'], inplace=True)

In [8]:
frequent_item_sets = apriori(movies_standard, min_support=0.003, use_colnames=True)
print(frequent_item_sets)

D:\soft\python\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:113: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  DeprecationWarning,

       support                   itemsets
0     0.005486                      (丁乃筝)
1     0.003658                      (万梓良)
2     0.005121                      (中孝介)
3     0.003292                       (仇泠)
4     0.003292                      (任贤齐)
...        ...                        ...
1389  0.003292  (梁洛施, 陈意涵, 杨丞琳, 沈建宏, 是元介)
1390  0.004389   (林美秀, 那维勋, 纳豆, 朱芷莹, 白歆惠)
1391  0.003658   (谢依霖, 杨幂, 柯震东, 郭碧婷, 郭采洁)
1392  0.004023  (柯佳嬿, 蓝正龙, 猪哥亮, 赵正平, 王彩桦)
1393  0.003658   (阿部力, 瑞莎, 王柏杰, 胡婷婷, 邰智源)

[1394 rows x 2 columns]

In [10]:
frequent_item_sets.sort_values(by='support',ascending=False)

      support         itemsets
72   0.034016            (庹宗华)
82   0.030724            (张孝全)
108  0.029627            (戴立忍)
44   0.027798            (周杰伦)
146  0.027432            (杨祐宁)
..        ...              ...
126  0.003292            (李冰冰)
811  0.003292  (凤小岳, 张孝全, 桂纶镁)
810  0.003292  (凤小岳, 张书豪, 桂纶镁)
809  0.003292  (凤小岳, 张书豪, 张孝全)
840  0.003292    (史磊, 王小毅, 肖扬)

[1394 rows x 2 columns]

In [12]:
# 计算规则，并设置提升度阈值为 1.25 （返回的是各个指标的数值，可以按照按兴趣的指标排序观察，但具体解释还得参考实际数据的含义）
rules = association_rules(frequent_item_sets, metric='confidence', min_threshold=0.7)
rules.sort_values(by='confidence',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
2510,"(纳豆, 周冬雨)","(蔡洁, 张孝全)",0.004755,0.004755,0.004755,1.000000,210.307692,0.004732,inf,1.000000
3044,"(徐娇, 庾澄庆)","(林晖闵, 桂纶镁)",0.003292,0.003292,0.003292,1.000000,303.777778,0.003281,inf,1.000000
3050,(庾澄庆),"(徐娇, 林晖闵, 桂纶镁)",0.003292,0.003292,0.003292,1.000000,303.777778,0.003281,inf,1.000000
4671,"(狄玫, 张震, 梅芳)","(廖淑珍, 舒淇)",0.004389,0.004389,0.004389,1.000000,227.833333,0.004370,inf,1.000000
3048,"(庾澄庆, 桂纶镁)","(徐娇, 林晖闵)",0.003292,0.003292,0.003292,1.000000,303.777778,0.003281,inf,1.000000
...,...,...,...,...,...,...,...,...,...,...
403,(中孝介),"(范逸臣, 马念先)",0.005121,0.003658,0.003658,0.714286,195.285714,0.003639,3.487198,1.000000
85,(周渝民),(陈楚生),0.005121,0.003658,0.003658,0.714286,195.285714,0.003639,3.487198,1.000000
83,(周渝民),(陈嘉桦),0.005121,0.006218,0.003658,0.714286,114.873950,0.003626,3.478237,0.996397
398,(中孝介),"(马念先, 田中千绘)",0.005121,0.003658,0.003658,0.714286,195.285714,0.003639,3.487198,1.000000
903,"(周群达, 林依晨)",(王毓雅),0.007315,0.005121,0.005121,0.700000,136.700000,0.005083,3.316264,1.000000

# 3

In [15]:
mov=movi2[['电影名','主演']]
mov.head()

             电影名                         主演
11052       千与千寻    柊瑠美|入野自由|夏木真理|菅原文太|中村彰男
11053      你的名字。  神木隆之介|上白石萌音|长泽雅美|市原悦子|成田凌
11054         告白     松隆子|冈田将生|木村佳乃|西井幸人|桥本爱
11055        入殓师    本木雅弘|广末凉子|山崎努|吉行和子|笹野高史
11056  被嫌弃的松子的一生   中谷美纪|瑛太|香川照之|市川实日子|伊势谷友介

In [16]:
# 第一步，将原始数据转化为标准格式
movies_standard = mov.drop('主演', 1).join(mov['主演'].str.get_dummies())

D:\soft\python\Lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [17]:
movies_standard.columns

Index(['电影名', '2代目', 'AAA', 'AKB48', 'Aleksandr Filippenko', 'Andrei Boltnev',
       'Arif Herati', 'Asami Katsura 桂亚沙美', 'Azumi', 'Brother Tom',
       ...
       '鼻肇', '齐川爱', '齐藤壮马', '齐藤庆太', '齐藤由贵', '齐藤祥太', '齐藤贵美子', '齐藤阳一郎', '龙星凉',
       '龟梨和也'],
      dtype='object', length=4561)

In [18]:
# 利用mlxtend提供的apriori算法函数得到频繁项集，其中设置最小支持度为0.05
movies_standard.set_index(['电影名'], inplace=True)

In [19]:
frequent_item_sets = apriori(movies_standard, min_support=0.005, use_colnames=True)
print(frequent_item_sets)

D:\soft\python\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:113: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  DeprecationWarning,

      support      itemsets
0    0.010358        (三浦友和)
1    0.010358        (三船敏郎)
2    0.005346        (上野树里)
3    0.006237        (东出昌大)
4    0.007239        (中井和哉)
..        ...           ...
113  0.005569         (高山南)
114  0.009132        (高良健吾)
115  0.007239       (麻生久美子)
116  0.007462         (黑木华)
117  0.006571  (倍赏千惠子, 渥美清)

[118 rows x 2 columns]

In [20]:
frequent_item_sets.sort_values(by='support',ascending=False)

      support itemsets
37   0.016149    (宫崎葵)
68   0.013810   (染谷将太)
75   0.012696   (浅野忠信)
108  0.011917   (长泽雅美)
17   0.011805  (倍赏千惠子)
..        ...      ...
81   0.005123   (生田斗真)
82   0.005123   (田中丽奈)
61   0.005012   (木村文乃)
57   0.005012   (日笠阳子)
95   0.005012    (绪形拳)

[118 rows x 2 columns]

In [21]:
# 计算规则，并设置提升度阈值为 1.25 （返回的是各个指标的数值，可以按照按兴趣的指标排序观察，但具体解释还得参考实际数据的含义）
rules = association_rules(frequent_item_sets, metric='confidence', min_threshold=0.05)
rules.sort_values(by='confidence',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
1,(渥美清),(倍赏千惠子),0.007128,0.011805,0.006571,0.921875,78.08977,0.006487,12.648892,0.994281
0,(倍赏千惠子),(渥美清),0.011805,0.007128,0.006571,0.556604,78.08977,0.006487,2.239244,0.998988

# 3

In [81]:
mov=movi2[['电影名','主演']]
mov.head()

          电影名                   主演
13931  我的野蛮女友   车太贤|全智贤|金仁文|金太贤|任豪
13932   阳光姐妹淘  沈恩京|闵孝琳|姜素拉|南宝拉|陈熙京
13933    春光乍泄           张国荣|梁朝伟|张震
13934  假如爱有天意  孙艺珍|曹承佑|赵寅成|李己雨|金秉玉
13935    恐怖直播      河正宇|李璟荣|全慧珍|李大为

In [82]:
# 第一步，将原始数据转化为标准格式
movies_standard = mov.drop('主演', 1).join(mov['主演'].str.get_dummies())

D:\soft\python\Lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [83]:
movies_standard.columns

Index(['电影名', '??', '???', '???(Lee Han-bit)', '???(Yoon Seol-hui)',
       'Benjamin R?rstad', 'Benjamin Rørstad', 'Big Bang', 'Brantley Black',
       'Bruce Cornwell',
       ...
       '지은서', '지정남', '지훈', '진선규', '차영옥', '최형렬', '탁우석 Tak woosuk', '하울', '李昌龙',
       '李锡俊'],
      dtype='object', length=1667)

In [84]:
# 利用mlxtend提供的apriori算法函数得到频繁项集，其中设置最小支持度为0.05
movies_standard.set_index(['电影名'], inplace=True)

In [85]:
frequent_item_sets = apriori(movies_standard, min_support=0.005, use_colnames=True)
print(frequent_item_sets)

D:\soft\python\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:113: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  DeprecationWarning,

      support    itemsets
0    0.016963       (严志媛)
1    0.012671       (严正化)
2    0.005314       (严泰雄)
3    0.016759       (任昌丁)
4    0.007971        (元斌)
..        ...         ...
214  0.005722  (黄政民, 吴达洙)
215  0.005722  (朴仁焕, 罗文姬)
216  0.005518  (柳海真, 金允石)
217  0.005722  (河正宇, 赵震雄)
218  0.005518  (郑雄仁, 郑俊镐)

[219 rows x 2 columns]

In [86]:
frequent_item_sets.sort_values(by='support',ascending=False)

      support itemsets
19   0.036583    (吴达洙)
142  0.024320    (车太贤)
115  0.023503    (河正宇)
31   0.023094    (孙艺珍)
209  0.020846    (黄政民)
..        ...      ...
175  0.005109    (金敏贞)
177  0.005109    (金晶恩)
67   0.005109    (朴勇宇)
185  0.005109    (金玉彬)
138  0.005109    (赵成夏)

[219 rows x 2 columns]

In [87]:
# 计算规则，并设置提升度阈值为 1.25 （返回的是各个指标的数值，可以按照按兴趣的指标排序观察，但具体解释还得参考实际数据的含义）
rules = association_rules(frequent_item_sets, metric='confidence', min_threshold=0.05)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(任昌丁),(金秀美),0.016759,0.014306,0.005109,0.304878,21.310976,0.004870,1.418016,0.969320
1,(金秀美),(任昌丁),0.014306,0.016759,0.005109,0.357143,21.310976,0.004870,1.529487,0.966909
2,(赵震雄),(吴达洙),0.017167,0.036583,0.005109,0.297619,8.135475,0.004481,1.371645,0.892402
3,(吴达洙),(赵震雄),0.036583,0.017167,0.005109,0.139665,8.135475,0.004481,1.142383,0.910386
4,(金明民),(吴达洙),0.009810,0.036583,0.006540,0.666667,18.223464,0.006181,2.890251,0.954489
5,(吴达洙),(金明民),0.036583,0.009810,0.006540,0.178771,18.223464,0.006181,1.205742,0.981014
6,(黄政民),(吴达洙),0.020846,0.036583,0.005722,0.274510,7.503779,0.004960,1.327953,0.885187
7,(吴达洙),(黄政民),0.036583,0.020846,0.005722,0.156425,7.503779,0.004960,1.160719,0.899645
8,(朴仁焕),(罗文姬),0.006540,0.014102,0.005722,0.875000,62.048913,0.005630,7.887186,0.990361
9,(罗文姬),(朴仁焕),0.014102,0.006540,0.005722,0.405797,62.048913,0.005630,1.671921,0.997957
10,(柳海真),(金允石),0.016350,0.017167,0.005518,0.337500,19.659375,0.005237,1.483521,0.964910
11,(金允石),(柳海真),0.017167,0.016350,0.005518,0.321429,19.659375,0.005237,1.449590,0.965712
12,(河正宇),(赵震雄),0.023503,0.017167,0.005722,0.243478,14.182609,0.005319,1.299147,0.951863
13,(赵震雄),(河正宇),0.017167,0.023503,0.005722,0.333333,14.182609,0.005319,1.464746,0.945727
14,(郑雄仁),(郑俊镐),0.009401,0.016554,0.005518,0.586957,35.456522,0.005362,2.380974,0.981019
15,(郑俊镐),(郑雄仁),0.016554,0.009401,0.005518,0.333333,35.456522,0.005362,1.485898,0.988155